// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIU1H5HuojY3i7Rchm2RR6KHF6LAH_GlA',
    appId: '1:138963826329:web:59349d97a3e45c95416a08',
    messagingSenderId: '138963826329',
    projectId: 'resident-evaluations',
    authDomain: 'resident-evaluations.firebaseapp.com',
    storageBucket: 'resident-evaluations.appspot.com',
    measurementId: 'G-NHH65090BX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB1H8XWLzPQAxiD98EAYymv9aEssCsBiU',
    appId: '1:138963826329:android:a6c600b84a85afe9416a08',
    messagingSenderId: '138963826329',
    projectId: 'resident-evaluations',
    storageBucket: 'resident-evaluations.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrB0JMI-4QgD1TK5QShZT84MjEBbhwJEY',
    appId: '1:138963826329:ios:81bacad94ac857f5416a08',
    messagingSenderId: '138963826329',
    projectId: 'resident-evaluations',
    storageBucket: 'resident-evaluations.appspot.com',
    iosClientId: '138963826329-h4brsg2c4gvfgc4dv1c52lcjttrp6keu.apps.googleusercontent.com',
    iosBundleId: 'com.rtype.ftEvaluations',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrB0JMI-4QgD1TK5QShZT84MjEBbhwJEY',
    appId: '1:138963826329:ios:81bacad94ac857f5416a08',
    messagingSenderId: '138963826329',
    projectId: 'resident-evaluations',
    storageBucket: 'resident-evaluations.appspot.com',
    iosClientId: '138963826329-h4brsg2c4gvfgc4dv1c52lcjttrp6keu.apps.googleusercontent.com',
    iosBundleId: 'com.rtype.ftEvaluations',
  );
}
